const KEY='instant-thought-inbox-v1';
const CATS=['全部','实验流程','实验学习','生活','德国'];
let filter='全部';
let notes=[];
const $=id=>document.getElementById(id);
const today=()=>new Date().toISOString().slice(0,10);
const nowTime=()=>new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function load(){try{notes=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{notes=[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(notes));render();makeWallpaper(false)}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function fmt(d,t){return `${d} ${t||''}`.trim()}
function addText(){const text=$('textInput').value.trim();if(!text)return;notes.unshift({id:uid(),type:'text',text,category:$('categoryInput').value,date:today(),time:nowTime(),done:false});$('textInput').value='';save()}
function delNote(id){notes=notes.filter(n=>n.id!==id);save()}
function toggleNote(id){notes=notes.map(n=>n.id===id?{...n,done:!n.done,doneAt:!n.done?new Date().toISOString():null}:n);save()}
function noteCard(n){const body=n.type==='drawing'?`<img src="${n.data}" alt="手写记录">`:`<div class="note-text">${escapeHtml(n.text)}</div>`;return `<article class="note ${n.done?'done':''}"><div class="note-main"><button class="check" data-toggle="${n.id}" aria-label="完成">${n.done?'✓':''}</button><div style="flex:1">${body}<div class="meta"><span class="tag">${n.category}</span><span>${fmt(n.date,n.time)}</span>${n.done?'<span>已完成</span>':'<span>未完成，会顺延</span>'}</div></div></div><div class="note-actions"><button class="danger" data-del="${n.id}">删除</button></div></article>`}
function putList(el,arr){el.innerHTML=arr.length?arr.map(noteCard).join(''):'<div class="empty">这里暂时没有内容。</div>'}
function render(){const d=today();$('todayLabel').textContent=new Date().toLocaleDateString('zh-CN',{weekday:'long',year:'numeric',month:'long',day:'numeric'});const selected=filter==='全部'?notes:notes.filter(n=>n.category===filter);const open=selected.filter(n=>!n.done);const todayItems=selected.filter(n=>n.date===d);$('openCount').textContent=open.length;$('openPill').textContent=open.length+' 条';$('todayPill').textContent=todayItems.length+' 条';$('allPill').textContent=selected.length+' 条';putList($('openList'),open);putList($('todayList'),todayItems);putList($('allList'),selected);renderChips()}
function renderChips(){const box=$('filterChips');box.innerHTML=CATS.map(c=>`<button class="chip ${c===filter?'active':''}" data-cat="${c}">${c}</button>`).join('')}
function exportData(){const blob=new Blob([JSON.stringify({app:'instant-thought-inbox',version:1,exportedAt:new Date().toISOString(),notes},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='思维收集箱备份-'+today()+'.json';a.click();URL.revokeObjectURL(a.href)}
async function importData(file){if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.notes))throw new Error('格式不对');notes=data.notes.concat(notes);save()}catch(e){alert('导入失败：'+e.message)}}
let ctx,drawing=false,last=null;
function setupCanvas(){const c=$('drawCanvas');ctx=c.getContext('2d');ctx.lineWidth=5;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#1f2933';ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);const pos=e=>{const r=c.getBoundingClientRect();const p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*c.width/r.width,y:(p.clientY-r.top)*c.height/r.height}};const start=e=>{e.preventDefault();drawing=true;last=pos(e)};const move=e=>{if(!drawing)return;e.preventDefault();const p=pos(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p};const end=()=>{drawing=false;last=null};['mousedown','touchstart'].forEach(x=>c.addEventListener(x,start,{passive:false}));['mousemove','touchmove'].forEach(x=>c.addEventListener(x,move,{passive:false}));['mouseup','mouseleave','touchend','touchcancel'].forEach(x=>c.addEventListener(x,end))}
function clearCanvas(){const c=$('drawCanvas');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height)}
function saveDrawing(){const c=$('drawCanvas');notes.unshift({id:uid(),type:'drawing',data:c.toDataURL('image/png'),category:$('handCategoryInput').value,date:today(),time:nowTime(),done:false});clearCanvas();save()}
function drawWallpaper(w=1290,h=2796){const c=$('wallpaperCanvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle='#f7f3ea';x.fillRect(0,0,w,h);x.fillStyle='#efe3d0';x.beginPath();x.arc(w*.82,h*.08,w*.34,0,7);x.fill();x.fillStyle='#1f2933';x.font=`700 ${Math.round(w*.075)}px -apple-system`;x.fillText('今日计划',w*.08,h*.11);x.font=`400 ${Math.round(w*.032)}px -apple-system`;x.fillStyle='#6b7280';x.fillText(new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}),w*.08,h*.155);const open=notes.filter(n=>!n.done).slice(0,8);let y=h*.23;x.fillStyle='#5d4630';x.font=`700 ${Math.round(w*.04)}px -apple-system`;x.fillText(`未完成 ${open.length} 条`,w*.08,y);y+=h*.045;open.forEach((n,i)=>{x.fillStyle='#fffaf3';roundRect(x,w*.07,y-h*.03,w*.86,h*.085,28,true);x.fillStyle='#5d4630';x.font=`700 ${Math.round(w*.027)}px -apple-system`;x.fillText(n.category,w*.1,y);x.fillStyle='#1f2933';x.font=`400 ${Math.round(w*.031)}px -apple-system`;let text=n.type==='drawing'?'[手写记录]':n.text;wrapText(x,(i+1)+'. '+text,w*.1,y+h*.035,w*.78,h*.036,2);y+=h*.105});x.fillStyle='#6b7280';x.font=`400 ${Math.round(w*.026)}px -apple-system`;x.fillText('即时思维收集箱 · 打勾前自动顺延',w*.08,h*.94)}
function roundRect(x,a,b,w,h,r,fill){x.beginPath();x.moveTo(a+r,b);x.arcTo(a+w,b,a+w,b+h,r);x.arcTo(a+w,b+h,a,b+h,r);x.arcTo(a,b+h,a,b,r);x.arcTo(a,b,a+w,b,r);if(fill)x.fill()}
function wrapText(x,text,a,b,max,lineH,maxLines){let words=String(text).split(''),line='',lines=0;for(const ch of words){const test=line+ch;if(x.measureText(test).width>max&&line){x.fillText(line,a,b);b+=lineH;line=ch;lines++;if(lines>=maxLines-1){break}}else line=test}if(line)x.fillText(line.length>30?line.slice(0,30)+'…':line,a,b)}
function makeWallpaper(show=true){drawWallpaper(1290,2796);if(show)alert('已生成今日壁纸预览')}
function downloadCanvas(name,w,h){drawWallpaper(w,h);const a=document.createElement('a');a.download=name+'-'+today()+'.png';a.href=$('wallpaperCanvas').toDataURL('image/png');a.click()}
async function shareWallpaper(){drawWallpaper(1290,2796);const blob=await new Promise(r=>$('wallpaperCanvas').toBlob(r,'image/png'));const file=new File([blob],'今日计划壁纸.png',{type:'image/png'});if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:'今日计划壁纸'})}else{downloadCanvas('今日计划壁纸-竖屏',1290,2796)}}
function bind(){document.addEventListener('click',e=>{const t=e.target;if(t.dataset.toggle)toggleNote(t.dataset.toggle);if(t.dataset.del)delNote(t.dataset.del);if(t.dataset.cat){filter=t.dataset.cat;render()}});$('addTextBtn').onclick=addText;$('clearTextBtn').onclick=()=>$('textInput').value='';$('exportBtn').onclick=exportData;$('importInput').onchange=e=>importData(e.target.files[0]);$('clearCanvasBtn').onclick=clearCanvas;$('saveDrawingBtn').onclick=saveDrawing;$('makeWallpaperBtn').onclick=()=>makeWallpaper(true);$('downloadPortraitBtn').onclick=()=>downloadCanvas('今日计划壁纸-竖屏',1290,2796);$('downloadLandscapeBtn').onclick=()=>downloadCanvas('今日计划壁纸-横屏',2796,1290);$('shareWallpaperBtn').onclick=shareWallpaper;$('textInput').addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')addText()})}
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'))}
if(window.navigator.standalone)$('offlineStatus').textContent='主屏幕模式';
load();bind();setupCanvas();render();makeWallpaper(false);
